name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      NIX_SIGN_PRIVATE_KEY_FILE: /tmp/secret-key-priv.pem

    steps:
    - name: Tailscale
      uses: tailscale/github-action@v4
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:bhu-cicd
        ping: cosimo.elk-agama.ts.net,sheepro.elk-agama.ts.net

    - name: Create Nix signing key file
      run: |
        cat >"$NIX_SIGN_PRIVATE_KEY_FILE" <<'EOF'
        ${{ secrets.NIX_SIGN_PRIVATE_KEY }}
        EOF

    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v34
      with:
        nix_conf: |
          experimental-features = nix-command flakes
          secret-key-files = ${{ env.NIX_SIGN_PRIVATE_KEY_FILE }}
          download-buffer-size = 134217728

    - name: Setup cachix
      uses: cachix/cachix-action@v16
      with:
        name: bihua-university
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

    - name: Checkout code
      uses: actions/checkout@v5

    - name: Flake check
      run: nix flake check -vL

    # - name: Pre-build cosimo
    #   run: nix build .#nixosConfigurations.cosimo.config.system.build.toplevel
    #
    # - name: Pre-build sheepro
    #   run: nix build .#nixosConfigurations.sheepro.config.system.build.toplevel

    - name: Deploy to targets
      run: nix run .#deploy -- --skip-checks --targets .#sheepro --targets .#cosimo --ssh-user deploy --ssh-opts '-oStrictHostKeyChecking=no'

